-- MySQL Script generated by MySQL Workbench
-- Tue May  8 23:35:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_profile` (
  `id_user` INT NOT NULL,
  `nm_first` VARCHAR(45) NULL,
  `nm_middle` VARCHAR(45) NULL,
  `nm_last` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_address` (
  `id_address` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_address`, `id_user`),
  INDEX `fk_User_address_User_profile_idx` (`id_user` ASC),
  CONSTRAINT `fk_User_address_User_profile`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User_profile` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_role` (
  `cd_role_type` INT NOT NULL,
  `id_entity` INT NOT NULL,
  `in_status` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`cd_role_type`, `id_entity`, `id_user`),
  INDEX `fk_User_role_User_profile1_idx` (`id_user` ASC),
  CONSTRAINT `fk_User_role_User_profile1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User_profile` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
